# .github/workflows/feature_engineering.yml
name: Feature Engineering

on:
  push:
    branches: [ main ]
    paths:
      - 'feature_engieering.ipynb'
      - 'feature_engineering.py'
      - 'requirements.txt'
  schedule:
    # every day at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  feature_engineering:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🏗 Run feature engineering
        # if you have a .py script:
        run: |
          python feature_pipeline.py
        # or, to execute the notebook in CI:
        # run: |
        #   pip install papermill
        #   papermill feature_engieering.ipynb output/fe_output.ipynb