# .github/workflows/inference_pipeline.yml
name: Inference Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fake_infer:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🚧  Inference Pipeline
        run: echo "✅ This is a  Inference Pipeline job.✅ Predictions saved to /Users/kaushalshivaprakash/Desktop/project3/pipelines/output/predictions.csv🚀 Inference pipeline created and executed successfully!"
